categories:
  - title: 'Home Assistant Operating System'
    label: 'os'
  - title: 'Build System'
    label: 'build'
  - title: 'Raspberry Pi'
    label: 'board/raspberrypi'
  - title: 'Open Virtual Appliance'
    label: 'board/ova'
  - title: 'Generic x86-64'
    label: 'board/generic-x86-64'
  - title: 'Hardkernel ODROID'
    label: 'board/odroid'
  - title: 'ASUS Tinker'
    label: 'board/tinker'
filter-by-commitish: true
commitish: dev
template: |
  ## Changes

  $CHANGES
